### ISSUE TITLE
Add Websocket + JWT example to tutorial

### ISSUE THREAD

**Issue by johnthagen** [YegorDB/django-channels-auth-token-middlewares#5]
I'd like to use `SimpleJWTAuthTokenMiddleware` with a channels [`AsyncJsonWebsocketConsumer`](https://channels.readthedocs.io/en/stable/topics/consumers.html#asyncjsonwebsocketconsumer), but I've read various places that you can't pass the token in headers, but must pass the token in the query parameter due to Websocket limitations

- https://stackoverflow.com/a/67147270/
- https://testdriven.io/courses/taxi-react/websockets-part-one/#H-3-authenticating-socket-connections

So I'm wondering if it's possible to use these together. I first though perhaps the headers could be passed during the HTTP request that upgrades the connect to the websocket, but then they would probably be lost before the websocket begins?

I'd be happy to contribute to the tutorial if this is something that is even possible. If this is something possible, I was thinking that [`websocket-client`](https://github.com/websocket-client/websocket-client) could be used in the tutorial to demonstrate how to connect and pass a token to the `Consumer`.

**Comment by YegorDB** [comment]
Since WebSocket works over HTTP custom headers in handshake request would work well. In [section 1.2 RFC6455](https://datatracker.ietf.org/doc/html/rfc6455#section-1.2) is written "Additional header fields may also be present".
But there is no ability to add custom headers to [browser WebSocket constructor](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket). So I guess it is good idea to add ability to use [SimpleJWTAuthTokenMiddleware](https://github.com/YegorDB/django-channels-auth-token-middlewares/blob/master/channels_auth_token_middlewares/middleware/drf.py#L49) and [DRFAuthTokenMiddleware](https://github.com/YegorDB/django-channels-auth-token-middlewares/blob/master/channels_auth_token_middlewares/middleware/drf.py#L28) not only with headers. I will add it in next release.

In my opinion, there is no need to add tutorial with any libraries this project not directly depends on. Because a lot of them.

**Comment by johnthagen** [comment]
Here are a list of online resources I found about Django Channels + JWT. I think it would be great to have a single, tested Middleware like could live in this package that multiple users could use and contribute to.

- https://testdriven.io/courses/real-time-app-with-django-channels-and-angular/part-one-websockets-part-one/#H-3-authenticating-socket-connections
- https://hashnode.com/post/using-django-drf-jwt-authentication-with-django-channels-cjzy5ffqs0013rus1yb9huxvl
- https://stackoverflow.com/questions/65297148/django-channels-jwt-authentication/67147270#67147270
- https://stackoverflow.com/a/65437244
- https://github.com/django/channels/discussions/1771 (your post 😅)

**Comment by YegorDB** [comment]
> Here are a list of online resources I found about Django Channels + JWT.

Thanks for this research! I will study that resourses this week.

> I think it would be great to have a single, tested Middleware like could live in this package that multiple users could use and contribute to.

I totally agree.

**Comment by johnthagen** [comment]
@YegorDB Just checking in. I see you made some progress in the [`drf_query_string_tokens`](https://github.com/YegorDB/django-channels-auth-token-middlewares/tree/drf_query_string_tokens) branch. If you'd like a review or testing let me know.

**Comment by YegorDB** [comment]
@johnthagen You are welcome to review and test [PR](https://github.com/YegorDB/django-channels-auth-token-middlewares/pull/6) I've just created.

**Comment by johnthagen** [comment]
Closed in

- #6
